[package]
name = "bus"
version = "0.2.1"

description = "A lock-free, bounded, single-producer, multi-consumer, broadcast channel."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://jon.tsp.io/crates/bus"
homepage = "https://github.com/jonhoo/bus"
repository = "https://github.com/jonhoo/bus.git"

keywords = ["channel","broadcast","lock-free"]

license = "MIT/Apache-2.0"

[features]
bench = []

[dependencies]
time = "0.1"
num_cpus = "0.2"
atomic-option = "0.1"

[profile.release]
debug=true

[[bin]]
name = "bench"
path = "src/bench.rs"
