[package]
name = "bus"
version = "0.1.0"

description = "Provides a lock-free, bounded broadcast channel"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://jon.tsp.io/crates/bus"
homepage = "https://github.com/jonhoo/bus"
repository = "https://github.com/jonhoo/bus.git"

keywords = ["channel","broadcast","lock-free"]

license = "MIT/Apache-2.0"

[dependencies]
time = "0.1"

[profile.release]
debug=true

[[bin]]
name = "bench"
path = "src/bench.rs"
